version: '3.4'
services:
    db:
        image: "postgres:12"
        container_name: database
        environment: 
            - PGDATA=/var/lib/postgresql/data
            - POSTGRES_DB=stock-db
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_HOST_AUTH_METHOD=trust
        ports:
            - 5432:5432
        expose:
            - 5432
    

